doc/codi.txt
- Changed "Javscript" to "Javascript", after fixing that it threw off the alignment of the interpreters, so i returned the alignment to be as expected. 
- Changed "Result 2" to "Result 1", Not 100% sure if this was "wrong" but i fixed it due to when i was reading though it i became confused.
- Changed "forwardslashes" to "forward slashes"
- Changed "accomodate" to "accommodate"
- Changed "**is the a line**" to "**is a line**"
- Changed "preproccess" to "preprocess"
Please let me know if anything i changed needs to be changed back (such as the forwardslashes or the Result 2). I can make a change to the PR before you accept it. 
Also, for spelling errors, i suggest you look into `set spelllang=en_us` :) that's where i caught all of the spelling errors personally. If you would like an …
=> Fixed Spelling, Grammer, and Alignment

autoload/codi.vim, doc/codi.txt, plugin/codi.vim
Defaults to on. The way it works is by changing Vim's current
working directory to match the directory of the file buffer
before starting the REPL. It changes the cwd back to what it
originally was to minimize side effects. This can make it easier
for the users code to use path relative to that script. I tried
changing the cwd option passed to jobstart() for Neovim, but
that did not seem to have any effect. Let me know if you have
an idea for a cleaner, more side effect free way of achieving
this. I don't mind if you want this to default to off instead.
=> Option to start the REPL from the buffer directory

README.md, autoload/codi/load.vim, doc/codi.txt
Using [planck](http://planck-repl.org/). Originally tried several alternatives
- `lein repl` takes much longer
- `grench repl` was instant but requires a `project.clj` file, starting up a headless REPL to (re)connect to (state issues) and can't parse multiline s-expressions.
In the spirit of k.i.s.s, I think this is the way to go, though launching [planck's socket REPL](http://planck-repl.org/socket-repl.html) and (re)connecting to it may make things faster (currently not in their Linux release [yet](https://github.com/mfikes/planck/pull/297), and I don't has OSX to test that out).
=> Clojure/Clojurescript support via Planck (~1 sec lag) (fixes #34)

autoload/codi/load.vim
Now that custom node REPL behavior is specified, it is a good idea
to enable the global context. If the standard REPL was being used,
the global context would be used. Also, when not running as a REPL,
node normally uses this context, so this option prevents the REPL
from further deviating from normal node behavior. Some JavaScript
code relies on the global context to work correctly.
=> restored normal node global context behavior:

autoload/codi/load.vim
Python's `$PYTHONSTARTUP` and Ruby's `~/.irbrc` files can interfere with the default `g:codi#interpreters` values, like `prompt`.
This change turns those configurations off so that Codi works out of the box.
See [Issue #31](https://github.com/metakirby5/codi.vim/issues/31#issuecomment-251570996) for more info.
=> Ignore python and ruby config files

autoload/codi/load.vim
When using a Funcref value in `g:codi#interpreters` the following error
would be thrown:
> E704: Funcref variable name must start with a capital: v
This changes the code to use `V` instead of `v`.
=> Fix s:deep_extend for funcrefs

README.md, autoload/codi.vim, autoload/codi/load.vim, doc/codi.txt
PureScript/PSCi is very similar to Haskell/GHCi.  It is a bit weird though in that multi-line input is started with a ":paste" command and ended with Ctrl-d. (Yes, the same Ctrl-d that shuts down the interpreter) It took me a bit to figure out that it takes 4 keypresses in the vim buffer to send this through to the interpreter:
Ctrl-v Ctrl-v Ctrl-v Ctrl-d
(Which appears as ^V^D)
So I added a note about that in the documentation. If you think that's too rough for the average user to handle I have a rephrase function that let's you get by with just Ctrl-v Ctrl-d or an ":endpaste" command instead.
=> Added support for PureScript's PSCi interpreter

autoload/codi.vim
The PR proposed to resolve the ExtraWhiteSpace issue, which vim takes as a bad character.
=> Fix a issue that generates ExtraWhiteSpace

autoload/codi/load.vim, doc/codi.txt
Insert # in the blank lines above Python's class methods definition to avoid `IndentationError`
=> fix Python's IndentationError issue

autoload/codi/load.vim
For PHP code, ignores the PHP start tag if it appears at the very beginning of the buffer. #67
=> Ignoring PHP start tag at beginning of buffer

autoload/codi.vim
I have `set signcolumn=yes` in my nvim config, which makes it so the sign column is always displayed. I don't really want that in the codi buffer, but more importantly it actually breaks the right aligned UI. When it is enabled the output in the codi buffer is off 'screen' because the textwidth is being set using the window width, which isn't necessarily the same as amount of screen real estate that the buffer content is afforded. 
To fix the problem of the text being shifted off screen I simply added the `signcolumn=no` to the filetype set up
=> Fixing issue where signcolumn breaks codi buffer ui

autoload/codi/load.vim
With this changes codi does't hang on input like `[1..]`, but there's a bug where the output is delayed by two lines. [https://asciinema.org/a/0N5Rf6KbY2wBnaiJgt6LAzUoy](https://asciinema.org/a/0N5Rf6KbY2wBnaiJgt6LAzUoy)
It's likely because the runtime doesn't like how the rephraser adds lines to the buffer. I'm not sure what to change.
=> Improving Haskell compatability

README.md, autoload/codi/load.vim, doc/codi.txt
Depends on https://github.com/HerringtonDarkholme/typescript-repl/pull/35
=> Add typescript repl support

autoload/codi.vim, plugin/codi.vim
Hi @megalithic , thank you for this fantastic plugin, I like it very much!
I just add this config to my `vimrc` to specify the python interpreter version
```vim
let g:codi#interpreters = {
\ 'python3': {
\ 'bin': 'python3',
\ 'prompt': '^\(>>>\|\.\.\.\) '
\ },
\ 'python2': {
\ 'bin': 'python2',
\ 'prompt': '^\(>>>\|\.\.\.\) '
\ }
\ }
```
I typed `:Codi py` and pressed `<Tab>` to get my own interpreter name, only to find `python`. This PR add the command-line complete function for user-defined interpreters support.
=> Allow to complete user defined interpreters in `:Codi`

autoload/codi.vim
For my setup it fixes #62 
```
Linux 7 5.1.7-arch1-1-ARCH #1 SMP PREEMPT Tue Jun 4 15:47:45 UTC 2019 x86_64 GNU/Linux
vim 8.1
fish 3.02
```
=> Fix /usr/bin/script execution on non standard shell

autoload/codi.vim
In [issue 122](https://github.com/metakirby5/codi.vim/issues/122) the exception catching is the problem. The first commit handles this.
The second commit adds some style fixes recommended by [Vint](https://github.com/Vimjas/vint).
=> Fix vim 8.2 errors

autoload/codi.vim
When you ran `:Codi!`, the virtual text is not cleared. This PR fixes this.
=> fix when codi is toggled, virtual text was not cleared

autoload/codi.vim
This PR solves the problem described in issue #130 on my setup:
- Linux 5.10.4-arch2-1 SMP PREEMPT Fri, 01 Jan 2021 05:29:53 +0000 x86_64 GNU/Linux
- Neovim 0.4.4
- Python 3.9.1
=> Fix error with Python and Neovim

autoload/codi.vim
This PR resolves #144, but I'm really not sure why. It was tested on the vim version and operating system stated in #144. Seems like it could be related to some internal vim 8.2 issues.
It uses `winsaveview()` and `winrestview()` to change the cursor position (if I switch back to your `cursor()` usage, the error to return), and issues an `<Esc>` to normal mode after updating the window (without which, again, the error returns -- note this replaces the `normal! kj` I used in the kludge mentioned in #144).
=> Fix codi syncbind issues

README.md
I don't have Python 2 installed on my system, so Codi wasn't working for Python. It took me a while to figure out that Codi wasn't using Python 3. I figure there should be a note in the readme. (Maybe you would want to update the vim docs later, too...)
The note I added isn't really enough detail (I spent all of five minutes on it), but hopefully it's enough information to point users in the right direction.
=> Add note in Readme about Python 3 config

README.md, autoload/codi/load.vim, doc/codi.txt
This adds support for the [Haxe](https://haxe.org) language,
thanks to the [ihx](https://lib.haxe.org/p/ihx/) interpreter.
(It has some display glitches here and there sometimes when typing,
but I have been using it for years.)
=> add Haxe support

autoload/codi.vim, doc/codi.txt
This PR adds an option `codi#virtual_text_pos` option that allow one to specify the position of the virtual text.
The default option is still `eof` but one can select `right_align` to have the text at the end of the window or a number can be specified to have the text align nicely at the specified column,
=> Add codi#virtual_text_pos option

autoload/codi.vim
Hi, Codi seems to be clearing extmarks from other plugins.
I tested this change and it seems to work, but I'm not really familiar with this plugin, so please do tell me if there's any other thing I should change
fixes m-demare/hlargs.nvim#28
=> All extmark namespaces are being cleared

autoload/codi/load.vim
I had the same issue as https://github.com/metakirby5/codi.vim/issues/133
This change fixed it
Thanks for the awesome plugin btw ❤️
=> Fix codi not working in Ruby
